name: CI

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, feature/**, fix/** ]

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: strivo_test
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres -d strivo_test"
          --health-interval=10s --health-timeout=5s --health-retries=5

      redis:
        image: redis:7
        ports: ['6379:6379']
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      RAILS_ENV: test
      SECRET_KEY_BASE: dummy_key_for_ci
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/strivo_test
      REDIS_URL: redis://localhost:6379/1
      BUNDLE_WITHOUT: production

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: false

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config \
                                  libpq-dev postgresql-client \
                                  libvips

      - name: Install gems
        run: |
          gem install bundler -v 2.5.18
          bundle _2.5.18_ install --jobs 4 --retry 3

      # Optioneel: zet chmod goed in CI zodat andere binstubs ook werken
      - name: Fix bin permissions (CI)
        run: chmod +x bin/* || true

      - name: Prepare DB
        run: bundle exec rails db:prepare

      - name: RSpec
        run: bundle exec rspec --format documentation --backtrace
